title: Adithya Chakravarthy
description: <br/>Email <a href="mailto:adithyachakra21@gmail.com">adithyachakra21[at]gmail[dot]com</a><br/>
logo: main_image.jpg
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false
